package com.kiki.constants;

import java.util.ArrayList;
import java.util.List;

public class Constants {
    public static List<String> FIELDS = new ArrayList<>();
    static {
        FIELDS.add("主料");
        FIELDS.add("主治");
        FIELDS.add("主题");
        FIELDS.add("人群");
        FIELDS.add("体质");
        FIELDS.add("作用");
        FIELDS.add("做法");
        FIELDS.add("内容");
        FIELDS.add("出处");
        FIELDS.add("分类");
        FIELDS.add("功能");
        FIELDS.add("名家");
        FIELDS.add("名称");
        FIELDS.add("备注");
        FIELDS.add("定位");
        FIELDS.add("循行");
        FIELDS.add("护理");
        FIELDS.add("效用");
        FIELDS.add("材料");
        FIELDS.add("来源");
        FIELDS.add("烹法");
        FIELDS.add("疾病");
        FIELDS.add("病候");
        FIELDS.add("症状");
        FIELDS.add("禁忌");
        FIELDS.add("综论");
        FIELDS.add("节气");
        FIELDS.add("范围");
        FIELDS.add("解剖");
        FIELDS.add("证候");
        FIELDS.add("诊断");
        FIELDS.add("调料");
        FIELDS.add("辨证");
        FIELDS.add("部位");
        FIELDS.add("配伍");
        FIELDS.add("配料");
        FIELDS.add("释义");
        FIELDS.add("附注");
        FIELDS.add("题名");
        FIELDS.add("做法 (1)");
        FIELDS.add("刺灸法");
        FIELDS.add("同义词");
        FIELDS.add("一级分类");
        FIELDS.add("临床分科");
        FIELDS.add("临床表现");
        FIELDS.add("二级分类");
        FIELDS.add("使用频次");
        FIELDS.add("其它疗法");
        FIELDS.add("养生分类");
        FIELDS.add("养生方法");
        FIELDS.add("养生禁忌");
        FIELDS.add("分证论治");
        FIELDS.add("包括穴位");
        FIELDS.add("单方验方");
        FIELDS.add("基础治疗");
        FIELDS.add("所属经络");
        FIELDS.add("推拿疗法");
        FIELDS.add("操作方法");
        FIELDS.add("操作要点");
        FIELDS.add("术语名称");
        FIELDS.add("术语编号");
        FIELDS.add("治疗原则");
        FIELDS.add("疾病名称");
        FIELDS.add("知识分类");
        FIELDS.add("穴位名称");
        FIELDS.add("经脉名称");
        FIELDS.add("经过器官");
        FIELDS.add("节气特点");
        FIELDS.add("西医疾病");
        FIELDS.add("鉴别诊断");
        FIELDS.add("饮食疗法");
        FIELDS.add("饮食类别");
        FIELDS.add("数据来源 (1)");
        FIELDS.add("下载时分类");
        FIELDS.add("中成药疗法");
        FIELDS.add("功效或作用");
        FIELDS.add("中医养生原理");
        FIELDS.add("二级知识分类");
        FIELDS.add("养生方法内容");
        FIELDS.add("养生方法名称");
        FIELDS.add("疗效评价方法");
        FIELDS.add("疗效评价标准");
        FIELDS.add("针灸穴位疗法");
        FIELDS.add("运动或功法名称 ");
    }
}
