package com.kiki.value;

import java.util.HashMap;
import java.util.Map;

public class ExtendEntityMap {
    final public static Map<String, String> FIELD_MAP = new HashMap<>();

    static {
        FIELD_MAP.put("主料", "zhu_liao");
        FIELD_MAP.put("主治", "zhu_zhi");
        FIELD_MAP.put("主题", "zhu_ti");
        FIELD_MAP.put("人群", "ren_qun");
        FIELD_MAP.put("体质", "ti_zhi");
        FIELD_MAP.put("作用", "zuo_yong");
        FIELD_MAP.put("做法", "zuo_fa");
        FIELD_MAP.put("内容", "nei_rong");
        FIELD_MAP.put("出处", "chu_chu");
        FIELD_MAP.put("分类", "fen_lei");
        FIELD_MAP.put("功能", "gong_neng");
        FIELD_MAP.put("名家", "ming_jia");
        FIELD_MAP.put("名称", "ming_cheng");
        FIELD_MAP.put("备注", "bei_zhu");
        FIELD_MAP.put("定位", "ding_wei");
        FIELD_MAP.put("循行", "xun_xing");
        FIELD_MAP.put("护理", "hu_li");
        FIELD_MAP.put("效用", "xiao_yong");
        FIELD_MAP.put("材料", "cai_liao");
        FIELD_MAP.put("来源", "lai_yuan");
        FIELD_MAP.put("烹法", "peng_fa");
        FIELD_MAP.put("疾病", "ji_bing");
        FIELD_MAP.put("病候", "bing_hou");
        FIELD_MAP.put("症状", "zheng_zhuang");
        FIELD_MAP.put("禁忌", "jin_ji");
        FIELD_MAP.put("综论", "zong_lun");
        FIELD_MAP.put("节气", "jie_qi");
        FIELD_MAP.put("范围", "fan_wei");
        FIELD_MAP.put("解剖", "jie_po");
        FIELD_MAP.put("证候", "zheng_hou");
        FIELD_MAP.put("诊断", "zhen_duan");
        FIELD_MAP.put("调料", "tiao_liao");
        FIELD_MAP.put("辨证", "bian_zheng");
        FIELD_MAP.put("部位", "bu_wei");
        FIELD_MAP.put("配伍", "pei_wu");
        FIELD_MAP.put("配料", "pei_liao");
        FIELD_MAP.put("释义", "shi_yi");
        FIELD_MAP.put("附注", "fu_zhu");
        FIELD_MAP.put("题名", "ti_ming");
        FIELD_MAP.put("做法 (1)", "zuo_fa_1");
        FIELD_MAP.put("刺灸法", "ci_jiu_fa");
        FIELD_MAP.put("同义词", "tong_yi_ci");
        FIELD_MAP.put("一级分类", "yi_ji_fen_lei");
        FIELD_MAP.put("临床分科", "lin_chuang_fen_ke");
        FIELD_MAP.put("临床表现", "lin_chuang_biao_xian");
        FIELD_MAP.put("二级分类", "er_ji_fen_lei");
        FIELD_MAP.put("使用频次", "shi_yong_pin_ci");
        FIELD_MAP.put("其它疗法", "qi_ta_liao_fa");
        FIELD_MAP.put("养生分类", "yang_sheng_fen_lei");
        FIELD_MAP.put("养生方法", "yang_sheng_fang_fa");
        FIELD_MAP.put("养生禁忌", "yang_sheng_jin_ji");
        FIELD_MAP.put("分证论治", "fen_zheng_lun_zhi");
        FIELD_MAP.put("包括穴位", "bao_kuo_xue_wei");
        FIELD_MAP.put("单方验方", "dan_fang_yan_fang");
        FIELD_MAP.put("基础治疗", "ji_chu_zhi_liao");
        FIELD_MAP.put("所属经络", "suo_shu_jing_luo");
        FIELD_MAP.put("推拿疗法", "tui_na_liao_fa");
        FIELD_MAP.put("操作方法", "cao_zuo_fang_fa");
        FIELD_MAP.put("操作要点", "cao_zuo_yao_dian");
        FIELD_MAP.put("术语名称", "shu_yu_ming_cheng");
        FIELD_MAP.put("术语编号", "shu_yu_bian_hao");
        FIELD_MAP.put("治疗原则", "zhi_liao_yuan_ze");
        FIELD_MAP.put("疾病名称", "ji_bing_ming_cheng");
        FIELD_MAP.put("知识分类", "zhi_shi_fen_lei");
        FIELD_MAP.put("穴位名称", "xue_wei_ming_cheng");
        FIELD_MAP.put("经脉名称", "jing_mai_ming_cheng");
        FIELD_MAP.put("经过器官", "jing_guo_qi_guan");
        FIELD_MAP.put("节气特点", "jie_qi_te_dian");
        FIELD_MAP.put("西医疾病", "xi_yi_ji_bing");
        FIELD_MAP.put("鉴别诊断", "jian_bie_zhen_duan");
        FIELD_MAP.put("饮食疗法", "yin_shi_liao_fa");
        FIELD_MAP.put("饮食类别", "yin_shi_lei_bie");
        FIELD_MAP.put("数据来源 (1)", "shu_ju_lai_yuan_1");
        FIELD_MAP.put("下载时分类", "xia_zai_shi_fen_lei");
        FIELD_MAP.put("中成药疗法", "zhong_cheng_yao_liao_fa");
        FIELD_MAP.put("功效或作用", "gong_xiao_huo_zuo_yong");
        FIELD_MAP.put("中医养生原理", "zhong_yi_yang_sheng_yuan_li");
        FIELD_MAP.put("二级知识分类", "er_ji_zhi_shi_fen_lei");
        FIELD_MAP.put("养生方法内容", "yang_sheng_fang_fa_nei_rong");
        FIELD_MAP.put("养生方法名称", "yang_sheng_fang_fa_ming_cheng");
        FIELD_MAP.put("疗效评价方法", "liao_xiao_ping_jia_fang_fa");
        FIELD_MAP.put("疗效评价标准", "liao_xiao_ping_jia_biao_zhun");
        FIELD_MAP.put("针灸穴位疗法", "zhen_jiu_xue_wei_liao_fa");
        FIELD_MAP.put("运动或功法名称", "yun_dong_huo_gong_fa_ming_cheng");
    }
}
